---
name: Dr. Hadis
surname: Rezaee
position: "PHd, Chemical Engineering"
address: "Tehran, Iran(Islamic Republic of)"
profilepic: "./img/me.png"
www: "hadisrezaee.org"
email: "h.s_rezaee@yahoo.com"
github: hadisrezaee
linkedin: hadis-rezaee-4a539a12a
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 990000
aboutme: "Hello, I am Dr. Hadis Rezaee, a performance-driven and self-motivated chemical engineering PhD candidate with over 5 years’ experience in oil and gas process and bitumen. Currently working for the my thesis work for investigating the effect of Mn-Na2WO4/SiO2 preparation Method on the performance of catalyst for Oxidative Coupling Methane. Enjoying overcoming challenges and aiming to apply my knowledge and decision-making skills to solve real-life situations for better performance and clean environment. Curiosity, aspiration for precision and passion for research has developed ingenious processes and products in the chemical world. I believe these qualities are what makes an enthusiastic and successful chemical engineering researcher."
docname: CV
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

require(xfun)

packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'      # String Manipulation
            )

xfun::pkg_attach2(packages, message = FALSE)

source(file = here("r","data.r"))

```

# Education

```{r EDUCATION}

edu %>%
  detailed_entries(
    with = inst,
    what = degree,
    why = detail,
    when = glue::glue("{startYear} --> {endYear}",.na = ""),
    where = where
  )

```

# Employment

```{r EMPLOYMENT}

work %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = ""),
    where = where
  )

```


\newpage
# Skills

```{r SKILLS}

skills %>%
  detailed_entries(
    with = area,
    what = skills
  )

```



<!--# Honors
-->

```{r HONORS, eval=FALSE}

honors %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )

```



# Publication Work

```{r WORKS}

works %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )

```

# Projects

```{r PROJECTS}

projects %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )

```



# Certifications

```{r CERTIFICATIONS}

certifications %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )

```


# References

```{r References}

references %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = ""),
    where = where
  )

```
